language: dart
dart:
  # Install the latest stable release
  - stable

dart_task:
  - test: --platform vm

  # Warnings are fatal, but we only analyze the lib/ directory.
  - dartanalyzer: --fatal-warnings lib

  - dartfmt